version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: certmgmt
      POSTGRES_PASSWORD: certmgmt
      POSTGRES_DB: certmgmt
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: